### ISSUE TITLE
-lsgx_tgmp

### ISSUE THREAD

**Issue by SHUJAA14** [Varad0612/SGX-LR#2]
I tried to run it but keeps showing me this error, can you please help 
GEN  =>  app/enclave_u.c
CXX   <=  app/enclave_u.c
CXX  <=  app/keygen.cpp
CXX  <=  app/encryptor.cpp
CXX  <=  app/pub_key.cpp
CXX  <=  app/App.cpp
CXX  <=  app/matrix.cpp
CXX  <=  app/logistic_regression.cpp
CXX  <=  app/helper.cpp
CXX  <=  app/evaluator.cpp
CXX  <=  app/context.cpp
CXX  <=  app/enclave_init.cpp
CXX  <=  tools/matrix_shared.cpp
CXX  <=  tools/sync_utils.cpp
CXX  <=  tools/secret_key.cpp
CXX  <=  tools/Queue.cpp
CXX  <=  tools/shared.cpp
/usr/bin/ld: cannot find -lsgx_tgmp
/usr/bin/ld: cannot find -lgmpxx
collect2: error: ld returned 1 exit status
Makefile:191: recipe for target 'a' failed
make: *** [a] Error 1

**Comment by Varad0612** [comment]
The error indicates that you might not have the [GMP library](https://gmplib.org/) installed locally. You would also need to install the [SGX GMP library](https://github.com/intel/sgx-gmp).

**Comment by SHUJAA14** [comment]
> The error indicates that you might not have the [GMP library](https://gmplib.org/) installed locally. You would also need to install the [SGX GMP library](https://github.com/intel/sgx-gmp).

x yes thank you i installed both libraries and it passed the previous error but now i have another error.
GEN  =>  app/enclave_u.c
CXX   <=  app/enclave_u.c
CXX  <=  app/keygen.cpp
CXX  <=  app/matrix.cpp
CXX  <=  app/pub_key.cpp
CXX  <=  app/encryptor.cpp
CXX  <=  app/logistic_regression.cpp
CXX  <=  app/App.cpp
CXX  <=  app/helper.cpp
CXX  <=  app/evaluator.cpp
CXX  <=  app/context.cpp
CXX  <=  app/enclave_init.cpp
CXX  <=  tools/matrix_shared.cpp
CXX  <=  tools/sync_utils.cpp
CXX  <=  tools/secret_key.cpp
CXX  <=  tools/Queue.cpp
CXX  <=  tools/shared.cpp
LINK =>  a
GEN  =>  enclave/enclave_t.c
CXX   <=  enclave/enclave_t.c
CXX  <=  enclave/Enclave.cpp
/usr/local/bin/ld: cannot open linker script file enclave/enclave.lds: No such file or directory
collect2: error: ld returned 1 exit status
Makefile:214: recipe for target 'enclave.so' failed
make: *** [enclave.so] Error 1

very much appreciated
